name: ligas_app
description: Plataforma web para la gestión de ligas y torneos
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  dio: ^5.4.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  file_picker: ^8.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
