version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: ligas_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ligas
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  backend:
    build:
      context: ../backend
    environment:
      APP_URL: http://localhost:3000
      FRONTEND_URL: http://localhost:8080
      DATABASE_URL: postgres://postgres:postgres@db:5432/ligas
      JWT_ACCESS_SECRET: change-me-access
      JWT_REFRESH_SECRET: change-me-refresh
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - backend-storage:/app/storage

  frontend:
    build:
      context: ../frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres-data:
  backend-storage:
